app1/urls.py
from django.urls import path
from app1.views import *

app_name='something'

urlpatterns=[
    path('krishna/',krishna,name='krishna'),
]

app2/urls.py
from django.urls import path
from app2.views import *

app_name='nothing'

urlpatterns=[
    path('radha/',radha,name='radha'),
]

project13/urls.py
from django.contrib import admin
from django.urls import path,include
import app1,app2

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def krishna(request):
    return render(request,'krishna.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def radha(request):
    return render(request,'radha.html')

templates/krishna.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center><h1>This is krishna html page</h1>
    <h1>This page belongs to app1</h1>

    <a href="{% url 'nothing:radha' %}">Go radha Page</a>
</center>
</body>
</html>

templates/radha.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center><h1>This is Radha html page</h1>
    <h1>This page belongs to app2</h1>

    <a href="{% url 'something:krishna' %}">Go krishna Page</a>
</center>
</body>
</html>